### ISSUE TITLE
/usr/bin/ld: cannot find -ll

### ISSUE THREAD

**Issue by BaseMax** [wan2land/mini-c#2]
Hi,

I have a question: what's `-ll` flag in gcc?
My system is Arch Linux and I don't know how to prepare **libl** package.

```bash
[max@base mini-c]$ make
bison -d minic.y
flex minic.l
gcc -o minic lex.yy.c minic.tab.c ucode.c minic_ast.c -ly -ll
/usr/bin/ld: cannot find -ll
collect2: error: ld returned 1 exit status
make: *** [Makefile:10: minic] Error 1
```

Thank you

**Comment by wan2land** [comment]
I worked in a macOS environment. It has built-in liby(yacc) and libl(lex).
I'm not sure, but if you're in a Linux environment, you can replace libfl.
